//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAO
{
    using System;
    using System.Collections.Generic;
    [Table("chitiethoadon")]

    public partial class ChiTietHoaDon
    {

        [Key, Column(Order = 0)]
        [ForeignKey("HoaDon")]
        public int MaHD { get; set; }
        [Key, Column(Order = 1)]
        [ForeignKey("SanPham")]
        public int MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string Size { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
