//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAO
{
    using System;
    using System.Collections.Generic;
    [Table("taikhoan")]

    public partial class TaiKhoan
    {
        [Key]
        public int ID { get; set; }
        public string TenTK { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<int> MaLoaiTK { get; set; }
        [ForeignKey("MaLoaiTK")]
        public virtual LoaiTK LoaiTK { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
